apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "s3-files-backup.fullname" . }}
  labels:
    {{- include "s3-files-backup.labels" . | nindent 4 }}
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    rule: RunAsAny
  allowedCapabilities:
    - '*'
  allowedHostPaths:
    - pathPrefix: "/backup"
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - configMap
    - persistentVolumeClaim
    - emptyDir
