{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "s3-files-backup.serviceAccountName" . }}
  labels:
{{ include "s3-files-backup.labels" . | nindent 4 }}
{{- end -}}
