
image:
  name: ghcr.io/icgc-argo/kafka-connect:latest
serviceAccount:
  create: true
  name: kafka-connect
kafkaSvcNamespace: "kafka-namespace"
kafkaSvcName: "kafka-headless"
replicaCount: 1
storage:
  size: 20Gi
topicList: t1,t2
sinkName: local-file-sink-backup
sinkPath: "/opt/bitnami/kafka/filesink"
restartTimeout: "24h"
nodeSelector:
  type: infra
tolerations:
  - key: type
    value: infra
backup:
  enabled: false
  retention: 7
encryptPassword: "encryptPassword"
targetPvcName: nfs-backup
loglevel: ERROR
