
image:
  name: bitnami/clinical-mongo:3.4.7
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  name: clinical-mongo-backup-dev
podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector:
  kubernetes.io/hostname: "gammaray-k8s-master-0"
tolerations: []
affinity: {}
schedule:  "55 */6 * * *"
nfsUserID: "1000"
targetPvcName: nfs-1
retention: "7"

backupConfigs:
  MONGO_HOST: host.docker.internal
  MONGO_PORT: 27017
  MONGO_DATABASE: clinical
  BACKUP_ID: clincal_mongo_dev
  VAULT_SECRET_PATH: kv/data/dev/clinical/secrets_v1
  VAULT_K8_ROLE: CLINICAL_MONGO_BACKUP_DEV
  VAULT_ADDR: https://vault.infra.argo.cancercollaboratory.org/