
image:
  name: icgcargo/backup-mongo:latest
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  name: lectern-backup-qa
podSecurityContext: {}
securityContext: {}
resources: {}
tolerations: []
affinity: {}
schedule:  "55 6 * * *"
targetPvcName: nfs-backup
retention: "7"
encryptPassword: "encrypt"

deployEnv: qa

backupConfigs:
  MONGO_HOST: mongo-host
  MONGO_PORT: 27017
  MONGO_DATABASE: mogo-db
  MONGO_REPLICASET: rs0
  BACKUP_ID: mongo-env
  VAULT_SECRET_PATH: kv/secret/mongo
  VAULT_K8_ROLE: mongo-role
  VAULT_ADDR: https://vault.local
