affinity: {}
backupConfigs:
  BACKUP_ID: mongo-env
  MONGO_DATABASE: mongo-db
  MONGO_HOST: mongo-host
  MONGO_PORT: 27017
  MONGO_REPLICASET: rs0
  VAULT_ADDR: https://vault.local
  VAULT_K8_ROLE: mongo-role
  VAULT_SECRET_PATH: kv/secret/mongo
deployEnv: qa
encryptPassword: encrypt
extraLabels: {}
fullnameOverride: ''
image:
  name: ghcr.io/icgc-argo/backup-mongo:latest
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ''
podSecurityContext: {}
psp:
  enable: false
resources: {}
retention: '7'
schedule: 55 6 * * *
securityContext: {}
serviceAccount:
  create: true
  name: lectern-backup-qa
targetPvcName: nfs-backup
tolerations: []
