{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "etcd-backup.serviceAccountName" . }}
  labels:
{{ include "etcd-backup.labels" . | nindent 4 }}
{{- end -}}
