affinity: {}
backupID: consul
consulSvcName: argo-vault-consulchart
consulSvcNamespace: smoke
deployEnv: infra
encryptPassword: ''
extraLabels: {}
fullnameOverride: ''
image:
  name: ghcr.io/icgc-argo/backup-consul:latest
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ''
nfsUserID: '1000'
podSecurityContext: {}
resources: {}
retention: '7'
schedule: 55 6 * * *
securityContext: {}
serviceAccount:
  create: true
  name: consul-backup
targetPvcName: nfs-1
tolerations: []
