def dockerRegistry = "ghcr.io"
def dockerRepo = "icgc-argo/backup-mongo"
def versionLabel = "org.icgc-argo.mongo-backup.version"
def imageVersion = ""

pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  name: docker-build
spec:
  volumes:
  - name: dind-storage
    emptyDir: {}
  securityContext:
    runAsUser: 1000
  containers:
  - name: docker
    image: docker:19.03.14-git
    command:
    - cat
    tty: true
    env:
    - name: DOCKER_HOST
      value: tcp://localhost:2375
    - name: HOME
      value: /home/jenkins/agent
  - name: dind
    image: docker:19.03.14-dind
    securityContext:
      privileged: true
      runAsUser: 0
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ''
    args: ["--registry-mirror", "https://registry.dev.argo.cancercollaboratory.org"]
    volumeMounts:
      - name: dind-storage
        mountPath: /var/lib/docker
"""
    }
  }

  options {
    disableConcurrentBuilds()
    timeout(time: 1, unit: 'HOURS')
  }

  triggers {
    cron(env.BRANCH_NAME == 'infra-nightly-builds' ? 'H 06 * * *' : '')
    pollSCM('H/4 12-22 * * 1-5')

  }

  stages {
    stage('Build and publish docker image') {
      when {
        branch "infra-nightly-builds"
      }
      steps {
        container('docker') {
          withCredentials([usernamePassword(credentialsId:'argoContainers', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
            sh "docker login ${dockerRegistry} -u $USERNAME -p $PASSWORD"
          }
          sh """
            cd docker/mongo
            docker build . -t ${dockerRegistry}/${dockerRepo}:latest
            imageVersion=`docker image inspect -f '{{ index .ContainerConfig.Labels "${versionLabel}" }}' ${dockerRegistry}/${dockerRepo}:latest`
            docker build . -t ${dockerRegistry}/${dockerRepo}:\$imageVersion
            docker push ${dockerRegistry}/${dockerRepo}:\$imageVersion
            docker push ${dockerRegistry}/${dockerRepo}:latest
          """
        }
      }
    }
  }
  post {
    unsuccessful {
      container("node") {
        script {
          if (env.BRANCH_NAME == "master" || env.BRANCH_NAME == "main" || env.BRANCH_NAME == "infra-nightly-builds") {
            withCredentials([string(credentialsId: 'DevOpsSlackJenkinsBuildAlerts', variable: 'JenkinsFailuresSlackChannelURL')]) { 
              sh "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"Build Failed: ${env.JOB_NAME} [${env.BUILD_NUMBER}] (${env.BUILD_URL}) \"}' ${JenkinsFailuresSlackChannelURL}"
            }
          }
        }
      }
    }
    fixed {
      container("node") {
        script {
          if (env.BRANCH_NAME == "master" || env.BRANCH_NAME == "main" || env.BRANCH_NAME == "infra-nightly-builds") {
            withCredentials([string(credentialsId: 'DevOpsSlackJenkinsBuildAlerts', variable: 'JenkinsFailuresSlackChannelURL')]) { 
              sh "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"Build Fixed: ${env.JOB_NAME} [${env.BUILD_NUMBER}] (${env.BUILD_URL}) \"}' ${JenkinsFailuresSlackChannelURL}"
            }
          }
        }
      }
    }
  }
}
