image:
  name: postgres:11.1
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: program-service-psql-backup-dev

podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector:
  kubernetes.io/hostname: "gammaray-k8s-master-0"
tolerations: []
affinity: {}

schedule:  "55 */6 * * *"
targetPvcName: nfs-backup
retention: "7"
encryptPassword: "encrypt"

backupConfigs:
  MONGO_HOST: program-service-argo-dev-postgres
  MONGO_PORT: 5432
  MONGO_DATABASE: program_service
  BACKUP_ID: program_service_psql_dev
  VAULT_SECRET_PATH: kv/dargo/dev/program-service
  VAULT_K8_ROLE: clinical-mongo-backup-dev
  VAULT_ADDR: https://vault.infra.argo.cancercollaboratory.org/