image:
  name: icgcargo/kube-infra:psql-backup-latest
  pullPolicy: Always

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: program-service-psql-backup-qa

podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector:
  kubernetes.io/hostname: "gammaray-k8s-master-0"
tolerations: []
affinity: {}

schedule:  "55 */6 * * *"
targetPvcName: nfs-backup
retention: "7"
encryptPassword: "encrypt"

deployEnv: "qa"

backupConfigs:
  PG_HOST: program-service-argo-qa-postgres.argo-qa
  PG_PORT: 5432
  PG_DATABASE: program_service
  BACKUP_ID: program_service_psql_qa
  VAULT_SECRET_PATH: kv/argo/qa/program-service
  VAULT_K8_ROLE: program-service-psql-backup-qa
  VAULT_ADDR: https://vault.infra.argo.cancercollaboratory.org/