
image:
  name: bitnami/etcd:3.4.7
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  name: etcd-backup
podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector:
  kubernetes.io/hostname: "kube-hostname"
tolerations: []
affinity: {}
schedule:  "55 6 * * *"
encryptPassword: ""
nfsUserID: "1000"
targetPvcName: nfs-1
retention: "7"