
image:
  name: ghcr.io/icgc-argo/backup-etcd:latest
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  name: etcd-backup
podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector:
  node-role.kubernetes.io/master: ""
tolerations: []
affinity: {}
schedule:  "55 6 * * *"
encryptPassword: ""
nfsUserID: "1000"
targetPvcName: nfs-1
retention: "7"
