affinity: {}
encryptPassword: ''
extraLabels: {}
fullnameOverride: ''
image:
  name: ghcr.io/icgc-argo/backup-etcd:latest
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ''
nfsUserID: '1000'
podSecurityContext: {}
resources: {}
retention: '7'
schedule: 55 6 * * *
securityContext: {}
serviceAccount:
  create: true
  name: etcd-backup
targetPvcName: nfs-1
#nodeSelector:
#  node-role.kubernetes.io/control-plane: ""
tolerations: []
