apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "consul-backup.fullname" . }}
  labels:
    {{- include "consul-backup.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule:  {{ .Values.schedule }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "consul-backup.labels" . | nindent 12 }}
            {{- with .Values.extraLabels }}
              {{ toYaml . | nindent 12 }}
            {{- end }}
        spec:
          containers:
            - name: backup
              image: {{ .Values.image.name }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: NFS_USER_ID
                  value: "{{ .Values.nfsUserID }}"
                - name: RETENTION
                  value: "{{ .Values.retention }}"
                - name: CONSUL_HTTP_ADDR
                  value: "{{ .Values.consulSvcName }}.{{ .Values.consulSvcNamespace }}.svc.cluster.local:8500"
                - name: BACKUP_ID
                  value: "{{ .Values.backupID }}-{{ .Values.consulSvcNamespace }}"
              command: ["/bin/sh"]
              args: ["/etc/consul-backup-script/backup.sh"]
              # args: ["-c","sleep 2000"]
              volumeMounts:
                - mountPath: /backup
                  name: backup
                - mountPath: /backup-target
                  name: backup-target
                - name: encrypt-key
                  mountPath: /etc/encrypt-key
                - mountPath: /etc/consul-backup-script
                  name: consul-backup-script
                  readOnly: true
          securityContext:
            runAsUser: 1001
          restartPolicy: OnFailure
          serviceAccountName: {{ include "consul-backup.serviceAccountName" . }}
          volumes:
            - name: backup
              emptyDir: {}
            - name: backup-target
              persistentVolumeClaim:
                claimName: {{ .Values.targetPvcName }}
            - name: encrypt-key
              secret:
                secretName:  {{.Values.deployEnv }}-consul-encrypt-key
            - configMap:
                name: consul-backup-script
              name: consul-backup-script
