apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "psql-backup.fullname" . }}
  labels:
    {{- include "psql-backup.labels" . | nindent 4 }}
rules:
- apiGroups:
  - policy
  resourceNames:
  - {{ include "psql-backup.fullname" . }}
  resources:
  - podsecuritypolicies
  verbs:
  - use
