pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  name: docker-build
spec:
  volumes:
  - name: dind-storage
    emptyDir: {}
  containers:
  - name: docker
    image: docker:19.03.14-git
    command:
    - cat
    tty: true
    env:
    - name: DOCKER_HOST
      value: tcp://localhost:2375
  - name: dind
    image: docker:19.03.14-dind
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ''
    args: ["--registry-mirror", "https://registry.dev.argo.cancercollaboratory.org"]
    volumeMounts:
      - name: dind-storage
        mountPath: /var/lib/docker
"""
    }
  }
  stages {
    stage('Build docker image with cache') {
      steps {
        container('docker') {
          sh "cd docker/psql && docker build --tag icgcargo/backup-psql:latest ."
        }
      }
    }
  }
}
