def dockerRepo = "ghcr.io/icgc-argo/backup-psql"
def imageVersion = "0.1.0"
pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  name: docker-build
spec:
  volumes:
  - name: dind-storage
    emptyDir: {}
  containers:
  - name: docker
    image: docker:19.03.14-git
    command:
    - cat
    tty: true
    env:
    - name: DOCKER_HOST
      value: tcp://localhost:2375
  - name: dind
    image: docker:19.03.14-dind
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ''
    args: ["--registry-mirror", "https://registry.dev.argo.cancercollaboratory.org"]
    volumeMounts:
      - name: dind-storage
        mountPath: /var/lib/docker
"""
    }
  }
  stages {
    stage('Build and publish docker image') {
      steps {
        container('docker') {
          withCredentials([usernamePassword(credentialsId:'argoContainers', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
            sh 'docker login ghcr.io -u $USERNAME -p $PASSWORD'
          }
          sh """
            cd docker/psql
            docker build . -t ${dockerRepo}:latest -t ${dockerRepo}:${imageVersion}
            docker push ${dockerRepo}:${imageVersion}
            docker push ${dockerRepo}:latest
          """
        }
      }
    }
  }
}
