apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "clinical-mongo-backup.fullname" . }}
  labels:
    {{- include "clinical-mongo-backup.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule:  {{ .Values.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: {{ .Values.image.name }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: MONGO_HOST
              value: "{{ .Values.backupConfigs.MONGO_HOST }}"
            - name: MONGO_PORT
              value: "{{ .Values.backupConfigs.MONGO_PORT }}"
            - name: BACKUP_ID
              value: "{{ .Values.backupConfigs.BACKUP_ID }}"
            - name: MONGO_DATABASE
              value: "{{ .Values.backupConfigs.MONGO_DATABASE }}"
            - name: VAULT_SECRET_PATH
              value: "{{ .Values.backupConfigs.VAULT_SECRET_PATH }}"
            - name: VAULT_K8_ROLE
              value: "{{ .Values.backupConfigs.VAULT_K8_ROLE }}"
            - name: VAULT_ADDR
              value: "{{ .Values.backupConfigs.VAULT_ADDR }}"
            - name: CLINICAL_MONGO_CTL_API
              value: "3"
            - name: NFS_USER_ID
              value: "{{ .Values.nfsUserID }}"
            - name: RETENTION
              value: "{{ .Values.retention }}"
            command: ["/bin/sh"]
            args: ["/etc/clinical-mongo-backup-script/backup.sh"]
            # args: ["-c","sleep 2000"]
            volumeMounts:
            - mountPath: /etc/clinical-mongo.env
              name: clinical-mongo-env
              readOnly: true
            - mountPath: /backup
              name: backup
            - mountPath: /backup-target
              name: backup-target
            - mountPath: /etc/clinical-mongo-backup-script
              name: clinical-mongo-backup-script
              readOnly: true
          securityContext:
            runAsUser: 0
          restartPolicy: OnFailure
          serviceAccountName: {{ include "clinical-mongo-backup.serviceAccountName" . }}
          tolerations:
          - effect: NoSchedule
            operator: Exists
          volumes:
          - name: clinical-mongo-env
            hostPath:
              path: /etc/clinical-mongo.env
              type: File
          - name: backup
            emptyDir: {}
          - name: backup-target
            persistentVolumeClaim:
              claimName: {{ .Values.targetPvcName }}
          - configMap:
              name: clinical-mongo-backup-script
            name: clinical-mongo-backup-script