apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "clinical-mongo-backup.fullname" . }}
  labels:
    {{- include "clinical-mongo-backup.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule:  {{ .Values.schedule }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "clinical-mongo-backup.labels" . | nindent 12 }}
            {{- with .Values.extraLabels }}
              {{ toYaml . | nindent 12 }}
            {{- end }}
        spec:
          containers:
            - name: backup
              image: {{ .Values.image.name }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: MONGO_HOST
                  value: "{{ .Values.backupConfigs.MONGO_HOST }}"
                - name: MONGO_PORT
                  value: "{{ .Values.backupConfigs.MONGO_PORT }}"
                - name: BACKUP_ID
                  value: "{{ .Values.backupConfigs.BACKUP_ID }}"
                - name: MONGO_DATABASE
                  value: "{{ .Values.backupConfigs.MONGO_DATABASE }}"
                - name: MONGO_REPLICASET
                  value: "{{ .Values.backupConfigs.MONGO_REPLICASET }}"
                - name: VAULT_SECRET_PATH
                  value: "{{ .Values.backupConfigs.VAULT_SECRET_PATH }}"
                - name: VAULT_K8_ROLE
                  value: "{{ .Values.backupConfigs.VAULT_K8_ROLE }}"
                - name: VAULT_ADDR
                  value: "{{ .Values.backupConfigs.VAULT_ADDR }}"
                - name: CLINICAL_MONGO_CTL_API
                  value: "3"
                - name: NFS_USER_ID
                  value: "{{ .Values.nfsUserID }}"
                - name: RETENTION
                  value: "{{ .Values.retention }}"
              command: ["/bin/sh"]
              args: ["/opt/clinical-mongo-backup-script/backup.sh"]
              # args: ["-c","sleep 200000"]
              volumeMounts:
                - mountPath: /backup
                  name: backup
                - mountPath: /backup-target
                  name: backup-target
                - name: encrypt-key
                  mountPath: /etc/encrypt-key
                - mountPath: /opt/clinical-mongo-backup-script
                  name: clinical-mongo-backup-script
                  readOnly: true
          restartPolicy: OnFailure
          serviceAccountName: {{ include "clinical-mongo-backup.serviceAccountName" . }}
          tolerations:
            - effect: NoSchedule
              operator: Exists
          volumes:
            - name: backup
              emptyDir: {}
            - name: backup-target
              persistentVolumeClaim:
                claimName: {{ .Values.targetPvcName }}
            - name: encrypt-key
              secret:
                secretName: {{.Values.deployEnv }}-clinical-mongo-encrypt-key
            - name: clinical-mongo-backup-script
              configMap:
                name: {{.Values.deployEnv }}-clinical-mongo-backup-script
