apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "clinical-mongo-backup.fullname" . }}
  labels:
    {{- include "clinical-mongo-backup.labels" . | nindent 4 }}
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    rule: RunAsAny
  allowedCapabilities:
  - '*'
  allowedHostPaths:
    - pathPrefix: "/backup"
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - configMap
  - persistentVolumeClaim
  - emptyDir
