apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "clinical-mongo-backup.fullname" . }}
  labels:
    {{- include "clinical-mongo-backup.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - policy
    resourceNames:
      - {{ include "clinical-mongo-backup.fullname" . }}
    resources:
      - podsecuritypolicies
    verbs:
      - use
