{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clinical-mongo-backup.serviceAccountName" . }}
  labels:
{{ include "clinical-mongo-backup.labels" . | nindent 4 }}
{{- end -}}
