{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jenkins-backup.serviceAccountName" . }}
  labels:
{{ include "jenkins-backup.labels" . | nindent 4 }}
{{- end -}}
