apiVersion: v1

kind: ConfigMap
metadata:
  name: {{ include "kafka-connect.fullname" . }}-backup
  labels:
    app.kubernetes.io/name: {{ include "kafka-connect.name" . }}
    helm.sh/chart: {{ include "kafka-connect.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  backup.sh: |-
    #!/bin/sh
    set -e
    DATA_PATH="{{ .Values.sinkPath }}"
    SNAP_PATH="/mnt/backup"
    SNAP_PATH_ENC="/mnt/backup_nfs_enc"
    RSNAP_CONFIG="/opt/bitnami/kafka/backupConfig/rsnapshot.conf"

    if [ ! -d  $DATA_PATH ]
      then
        echo "The path does not exist: $DATA_PATH"
        exit
    fi
    test -d  $SNAP_PATH || mkdir -p $SNAP_PATH
    test -d  $SNAP_PATH_ENC || mkdir -p $SNAP_PATH_ENC

    # use "standard" mode to allow rsnapshot hard links
    (mount | grep -w "$SNAP_PATH" | grep "type fuse.encfs" ) || (cat /etc/encrypt-key/password | encfs $SNAP_PATH_ENC $SNAP_PATH --standard -S)

    # rsnapshot
    rsnapshot -c $RSNAP_CONFIG alpha

    # cleanup
    fusermount -u $SNAP_PATH

  rsnapshot.conf: |-
    config_version	1.2
    snapshot_root	/mnt/backup
    cmd_cp		/bin/cp
    cmd_rm		/bin/rm
    cmd_rsync	/usr/bin/rsync
    cmd_logger	/usr/bin/logger
    cmd_rsnapshot_diff	/usr/bin/rsnapshot-diff
    retain	alpha	{{ .Values.backup.retention }}
    verbose		4
    loglevel	3
    lockfile	/var/run/backup/rsnapshot.pid
    rsync_short_args	-avz
    rsync_long_args	--delete	--numeric-ids	--relative	--delete-excluded
    backup	{{ .Values.sinkPath }}		localhost/
