apiVersion: v1

kind: ConfigMap
metadata:
  name: {{ include "kafka-connect.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "kafka-connect.name" . }}
    helm.sh/chart: {{ include "kafka-connect.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  connect.sh: |-
    #!/bin/sh
    set -e
    sink_name={{ .Values.sinkName }}
    sink_file=/opt/bitnami/kafka/filesink/${sink_name}-$(date +%Y-%m).sink
    sink_link="/opt/bitnami/kafka/filesink/kafka.sink"

    touch ${sink_file}
    [ -L ${sink_link} ] && ls -la ${sink_link} && echo "removing existing symlink..." && rm ${sink_link}

    ln -s ${sink_file} ${sink_link}

    test -w ${sink_file} || exit
    test -L ${sink_link} || exit

    echo "Current sink file: ${sink_file}"
    ls -la ${sink_file}

    timeout --preserve-status {{ .Values.restartTimeout }} /opt/bitnami/kafka/bin/connect-standalone.sh /opt/bitnami/kafka/custConfig/connect-standalone.properties /opt/bitnami/kafka/custConfig/connect-file-sink.properties

    ls -la ${sink_file}
    rm ${sink_link}

  connect-standalone.properties: |-
    bootstrap.servers=kafka-0.kafka-headless.kafka1.svc.cluster.local:9092
    key.converter=org.apache.kafka.connect.storage.StringConverter
    value.converter=org.apache.kafka.connect.storage.StringConverter
    key.converter.schemas.enable=false
    value.converter.schemas.enable=false
    offset.storage.file.filename=/tmp/connect.offsets
    offset.flush.interval.ms=10000
  connect-file-sink.properties: |-
    name={{ .Values.sinkName }}
    connector.class=FileStreamSink
    tasks.max=1
    file=/opt/bitnami/kafka/filesink/kafka.sink
    topics={{ .Values.topic }}
