apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kafka-connect.fullname" . }}
  labels:
    {{- include "kafka-connect.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kafka-connect.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kafka-connect.serviceAccountName" . }}
    namespace: {{ $.Release.Namespace }}
