{{- if .Values.authDelegator.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dac-mongo-backup.fullname" . }}
  labels:
    {{- include "dac-mongo-backup.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: {{ include "dac-mongo-backup.serviceAccountName" . }}
    namespace: {{ $.Release.Namespace }}
{{- end}}
