{{- if .Values.psp.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dac-mongo-backup.fullname" . }}
  labels:
    {{- include "dac-mongo-backup.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - policy
    resourceNames:
      - {{ include "dac-mongo-backup.fullname" . }}
    resources:
      - podsecuritypolicies
    verbs:
      - use
{{- end}}
