{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dac-mongo-backup.serviceAccountName" . }}
  labels:
{{ include "dac-mongo-backup.labels" . | nindent 4 }}
{{- end -}}
